#!/bin/bash

echo ' '
echo 'Dynamic Tests for the Main Method of cpsc331.assignment1.FGrindelwald'
echo ' '
echo 'Executing java.cpsc331.assignment1.FGrindelwald'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! One integer input is required.'
java cpsc331.assignment1.FGrindelwald
echo ' '
echo 'Rationale: No command-line inputs have been provided.'
echo ' '
echo ' '
echo 'Executing java.cpsc331.assignment1.FGrindelwald 2 4'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! One integer input is required.'
java cpsc331.assignment1.FGrindelwald 2 4
echo ' '
echo 'Rationale: More than one command-line input has been provided.'
echo ' '
echo ' '
echo 'Executing java.cpsc331.assignment1.FGrindelwald xy14'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! One integer input is required.'
java cpsc331.assignment1.FGrindelwald xy14
echo ' '
echo 'Rationale: The input is a string, rather than an integer.'
echo ' '
echo ' '
echo 'Executing java.cpsc331.assignment1.FGrindelwald -2'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! The integer input cannot be negative.'
java cpsc331.assignment1.FGrindelwald -2
echo ' '
echo 'Rationale: The input really is a negative integer.'
echo ' '
echo ' '
echo 'For all remaining tests, the input is a non-negative integer and'
echo 'the expected output is the corresponding Frindelwald number.'
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 0'
echo ' '
echo 'Expected and Actual Output:'
echo '1'
java cpsc331.assignment1.FGrindelwald 0
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 1'
echo ' '
echo 'Expected and Actual Output:'
echo '2'
java cpsc331.assignment1.FGrindelwald 1
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 2'
echo ' '
echo 'Expected and Actual Output:'
echo '3'
java cpsc331.assignment1.FGrindelwald 2
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 3'
echo ' '
echo 'Expected and Actual Output:'
echo '4'
java cpsc331.assignment1.FGrindelwald 3
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 4'
echo ' '
echo 'Expected and Actual Output:'
echo '5'
java cpsc331.assignment1.FGrindelwald 4
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 5'
echo ' '
echo 'Expected and Actual Output:'
echo '6'
java cpsc331.assignment1.FGrindelwald 5
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 6'
echo ' '
echo 'Expected and Actual Output:'
echo '7'
java cpsc331.assignment1.FGrindelwald 6
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 7'
echo ' '
echo 'Expected and Actual Output:'
echo '8'
java cpsc331.assignment1.FGrindelwald 7
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 8'
echo ' '
echo 'Expected and Actual Output:'
echo '9'
java cpsc331.assignment1.FGrindelwald 8
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 9'
echo ' '
echo 'Expected and Actual Output:'
echo '10'
java cpsc331.assignment1.FGrindelwald 9
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 10'
echo ' '
echo 'Expected and Actual Output:'
echo '11'
java cpsc331.assignment1.FGrindelwald 10
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.FGrindelwald 11'
echo ' '
echo 'Expected and Actual Output:'
echo '12'
java cpsc331.assignment1.FGrindelwald 11
echo ' '
echo ' '
