#!/bin/bash

echo ' '
echo 'Dynamic Tests for the Main Method of cpsc331.assignment1.SGrindelwald'
echo ' '
echo 'Executing java.cpsc331.assignment1.SGrindelwald'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! One integer input is required.'
java SGrindelwald
echo ' '
echo 'Rationale: No command-line inputs have been provided.'
echo ' '
echo ' '
echo 'Executing java.cpsc331.assignment1.SGrindelwald 2 4'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! One integer input is required.'
java SGrindelwald 2 4
echo ' '
echo 'Rationale: More than one command-line input has been provided.'
echo ' '
echo ' '
echo 'Executing java.cpsc331.assignment1.SGrindelwald xy14'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! One integer input is required.'
java SGrindelwald xy14
echo ' '
echo 'Rationale: The input is a string, rather than an integer.'
echo ' '
echo ' '
echo 'Executing java.cpsc331.assignment1.SGrindelwald -2'
echo ' '
echo 'Expected and Actual Output:'
echo 'Gadzooks! The integer input cannot be negative.'
java SGrindelwald -2
echo ' '
echo 'Rationale: The input really is a negative integer.'
echo ' '
echo ' '
echo 'For all remaining tests, the input is a non-negative integer and'
echo 'the expected output is the corresponding Grindelwald number.'
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 0'
echo ' '
echo 'Expected and Actual Output:'
echo '1'
java SGrindelwald 0
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 1'
echo ' '
echo 'Expected and Actual Output:'
echo '2'
java SGrindelwald 1
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 2'
echo ' '
echo 'Expected and Actual Output:'
echo '3'
java SGrindelwald 2
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 3'
echo ' '
echo 'Expected and Actual Output:'
echo '4'
java SGrindelwald 3
echo ' '
echo ' '
: '
echo 'Executing cpsc331.assignment1.SGrindelwald 4'
echo ' '
echo 'Expected and Actual Output:'
echo '5'
java cpsc331.assignment1.SGrindelwald 4
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 5'
echo ' '
echo 'Expected and Actual Output:'
echo '6'
java cpsc331.assignment1.SGrindelwald 5
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 6'
echo ' '
echo 'Expected and Actual Output:'
echo '7'
java cpsc331.assignment1.SGrindelwald 6
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 7'
echo ' '
echo 'Expected and Actual Output:'
echo '8'
java cpsc331.assignment1.SGrindelwald 7
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 8'
echo ' '
echo 'Expected and Actual Output:'
echo '9'
java cpsc331.assignment1.SGrindelwald 8
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 9'
echo ' '
echo 'Expected and Actual Output:'
echo '10'
java cpsc331.assignment1.SGrindelwald 9
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 10'
echo ' '
echo 'Expected and Actual Output:'
echo '11'
java cpsc331.assignment1.SGrindelwald 10
echo ' '
echo ' '
echo 'Executing cpsc331.assignment1.SGrindelwald 11'
echo ' '
echo 'Expected and Actual Output:'
echo '12'
java cpsc331.assignment1.SGrindelwald 11
echo ' '
echo ' '
'
